### PR TITLE
Correcting event Metadata fields mapping

### LINKED ISSUE #263: Event Metadata fields  mapping is wrong.
Hello Team,

Whenever CPE will try to connect to talaria, it will be sending the metadata parameters in convey headers and talaria will decode the convey header and persist it in memory. now the problem is there in parodus or talaria because parodus will be sending the key and talaria is expecting another key.

Here is a detailed view of the problem

Here [parodus](https://github.com/xmidt-org/parodus/blob/dee98922a667a5725bef240ead6ee8d5a7c6261d/src/ParodusInternal.c#L36) will be building convey header. with these all keys.

> hw-model
hw-serial-number
hw-manufacturer
hw-last-reboot-reason
fw-name
webpa-last-reconnect-reason
webpa-protocol
webpa-interface-used
boot-time-retry-wait
boot-time

and in [talaria](https://github.com/xmidt-org/talaria/blob/f104d3f4e39dfdfa8b1f0b44ef8590348e1ef495/deviceStatus.go#L14) we are expecting a few other fields.
> boot-time
hw-model
hw-manufacturer
hw-serial-number
hw-last-reboot-reason
fw-name
last-reconnect-reason
protocol

now there is a mismatch between the fields. we need to fix it either in parodus or in talaria.

cc: @schmidtw

### PR DESCRIPTION
**Pull request by Sachin4403**
closed #263

### CODE REVIEW

File: deviceStatus.go [hunk 1]
```diff
@@ -20,8 +20,10 @@ func statusMetadata(d device.Interface) map[string]string {
 		wrpmeta.Field{From: "hw-serial-number", To: "/hw-serial-number"},
 		wrpmeta.Field{From: "hw-last-reboot-reason", To: "/hw-last-reboot-reason"},
 		wrpmeta.Field{From: "fw-name", To: "/fw-name"},
-		wrpmeta.Field{From: "last-reconnect-reason", To: "/last-reconnect-reason"},
-		wrpmeta.Field{From: "protocol", To: "/protocol"}).
+		wrpmeta.Field{From: "webpa-last-reconnect-reason", To: "/last-reconnect-reason"},
```
Comment (schmidtw) [inline deviceStatus.go:23]: @johnabass is there a way to accept either `webpa-last-reconnect-reason` or `last-reconnect-reason` and map them to `/last-reconnect-reason` ?

Comment (Sachin4403) [reply deviceStatus.go:23]: Yes @schmidtw  we can add both fields, we just need to add this
```
wrpmeta.Field{From: "last-reconnect-reason", To: "/last-reconnect-reason"},
```

Logic is already written in wrp-go/blob/main/wrpmeta/metadata.go, if it is not able to find the filed then it will ignore the same,  problem here will be if we are getting both the fields in to convey header then the value will be overwritten  due to the same keys mentioned in `TO`

Comment (Sachin4403) [reply deviceStatus.go:24]: I had added the support in latest commit

**Comment by Sachin4403** [comment]
Hello @schmidtw  can we Merge this PR?

**Comment by schmidtw** [comment]
The failure is the Sonarcloud integration & nothing to do with the PR.
